x=rand(1,100)
figure(1)
plot(x)
title('random numbers')
xlabel('x random number')
ylabel('y random number')
figure(2)
stem(x)
title('random numbers')
xlabel('x random number')
ylabel('y random number')